from __future__ import annotations

from os import PathLike
from collections.abc import Callable
from typing import Any

from . import conventions as conventions

MEDIA_BASENAME_KEY: str
SIDECAR_EXTENSION: str

PHOTO_GPS_LATITUDE: str
PHOTO_GPS_LONGITUDE: str
PHOTO_EXPOSURE_TIME_SEC: str
PHOTO_EXPOSURE_ISO: str
PHOTO_LENS_FOCAL_LENGTH_MM: str
PHOTO_RATING: str
PHOTO_TAGS: str

class SidecarError(Exception): ...

class SidecarDocument:
    def __init__(self) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> SidecarDocument: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> SidecarDocument: ...
    @staticmethod
    def update_path(
        path: str | PathLike[str],
        updater: Callable[[SidecarDocument], None],
    ) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_path(self, path: str | PathLike[str]) -> None: ...
    def set(self, key: str, value: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def set_null(self, key: str) -> None: ...
    def set_bool(self, key: str, value: bool) -> None: ...
    def set_i64(self, key: str, value: int) -> None: ...
    def set_u64(self, key: str, value: int) -> None: ...
    def set_f32(self, key: str, value: float) -> None: ...
    def set_f64(self, key: str, value: float) -> None: ...
    def set_str(self, key: str, value: str) -> None: ...
    def set_bytes(self, key: str, value: bytes) -> None: ...
    def set_array(self, key: str, value: list[Any]) -> None: ...
    def set_map(self, key: str, value: dict[str, Any]) -> None: ...
    def remove(self, key: str) -> Any: ...
    def keys(self) -> list[str]: ...
    def entries(self) -> dict[str, Any]: ...
    def set_media_basename(self, basename: str) -> None: ...
    def media_basename(self) -> str | None: ...
    def header(self) -> dict[str, int | str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __repr__(self) -> str: ...
